[package]
name = "sentinel-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
sentinel-audit = { version = "0.1.0", path = "../audit" }
sentinel-crypto = { version = "0.1.0", path = "../crypto" }
sentinel-hardware = { version = "0.1.0", path = "../hardware" }
