[package]
name = "sentinel-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
hkdf = "0.12.4"
rand = "0.8.8"
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.10.9"
thiserror = "2.0.20"
vsss-rs = "6.0.1"
zeroize = "1.9.0"

[target."cfg(unix)".dependencies]
libc = "0.2"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_Memory"] }
